services:

  be:
    build: ./milan-be
    environment:
      DB_CON_STR: "dbname=chitti_apps user=milan password=isi4ja8# host=dpg-d7oca858nd3s738qt6pg-a port=5432"

  fe:
    build:
      context: ./milan-fe
      args:
        VITE_API_URL: /milan-aegis/api
        BASE_PATH: /milan-aegis-fe/
    ports:
      - "5000:5000"
    depends_on:
      - be
